project:
  type: website
  output-dir: docs
  resources:
    - relaxing.mp3
    - sharks!.png
    - UI pop up.mp3
    - UI pop back in.mp3

website:
  title: "Ariane Damian"

format:
  html:
    theme: none
    css: styles.css
    toc: false
    bootstrap-icons: true